### ISSUE TITLE
Bitbucket issue checklist

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/ALMA-TDA#2]
- [x] https://bitbucket.org/paulrosenphd/alma-tda/issues/15/build-script
- [x] https://bitbucket.org/paulrosenphd/alma-tda/issues/8/javadocs
- [x] https://bitbucket.org/paulrosenphd/alma-tda/issues/9/remove-fork-external-libraries
